name: Coreruleset Compatibility

on:
  push:
  pull_request:
  # Cron just in case the CRS team changed something and we are not compatible anymore
  # At 06:00 on Monday, Wednesday, and Friday
  schedule:
    - cron: '0 6 * * 1,3,5'
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 0 #for better blame info
    - name: Start httpbin
      run: docker run -p 8080:80 -d kennethreitz/httpbin
    - name: Setup CRS
      run: |
        git clone https://github.com/coreruleset/coreruleset
        cd coreruleset
        git checkout 6d8e8f8
        cd ..
        mv coreruleset /tmp
        cp coraza.conf-recommended /tmp/
        cp testdata/coreruleset/postdirectives.conf /tmp/
    - name: Go code
      working-directory: caddy
      run: |
        go build -o caddy .
        sudo setcap CAP_NET_BIND_SERVICE=+eip ./caddy
    - name: Start Caddy server
      run: |
        ./caddy/caddy start -adapter caddyfile -config ./testdata/coreruleset/Caddyfile
    - name: Run go-ftw
      run: |
        go run github.com/fzipi/go-ftw@latest run -d /tmp/coreruleset/tests/regression --config testdata/coreruleset/.ftw.yml
