name: Tinygo tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.23.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0 # for better blame info

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - name: Download vendored dependencies
        run: go mod vendor

      - name: Tests and coverage
        run: tinygo test ./...
